pipeline {
    agent any

    environment {
        TF_DIR = './task_2/terraform'
        ANSIBLE_DIR = './task_2/ansible'
        HOSTS_FILE = './task_2/ansible/hosts.ini'
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

    stages {
        stage('Terraform Init & Apply') {
            steps {
                dir("${TF_DIR}") {
                    sh '''
                        terraform init -input=false
                        terraform apply -auto-approve
                    '''
                }
            }
        }

        stage('Extract Terraform Outputs') {
            steps {
                dir("${TF_DIR}") {
                    script {
                        // Get outputs in JSON format
                        def tf_output = sh(script: 'terraform output -json', returnStdout: true).trim()
                        def parsed = readJSON text: tf_output

                        // Extract values
                        def web_ips = parsed.web_server_ips.value
                        def db_endpoint = parsed.db_endpoint.value

                        // Print for visibility
                        echo "Web IPs: ${web_ips}"
                        echo "DB Endpoint: ${db_endpoint}"

                        // Write hosts.ini dynamically
                        writeFile file: "${HOSTS_FILE}", text: """
[webservers]
${web_ips.collect { it + " ansible_user=ec2-user ansible_ssh_private_key_file=~/keys/test-key.pem" }.join('\n')}

[db]
${db_endpoint} ansible_user=ec2-user ansible_ssh_private_key_file=~/keys/test-key.pem
                        """.stripIndent()

                        echo "Generated hosts.ini successfully:"
                        sh "cat ${HOSTS_FILE}"
                        stash includes: "${HOSTS_FILE}", name 'hosts_file'
                    }
                }
            }
        }

        stage('Ansible Setup') {
            steps {
                dir("${ANSIBLE_DIR}") {
                    unstash 'hosts_file'
                    sh '''
                        ansible --version
                        echo "Inventory file:"
                        cat ${HOSTS_FILE}
                    '''
                }
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                dir("${ANSIBLE_DIR}") {
                    unstash 'hosts_file'
                    sh '''
                        ansible-playbook -i ${HOSTS_FILE} playbook.yml
                    '''
                }
            }
        }
    }

    post {
        failure {
            dir("${TF_DIR}") {
                echo "Pipeline failed. Terraform detroy"
                sh '''
                        terraform destroy -auto-approve
                    '''
                }
        }
    }
}


