pipeline {
    agent any

    environment {
        TF_DIR = 'terraform'
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

    stages {
        stage('Terraform Init & Apply') {
            steps {
                dir("./task_2/${TF_DIR}") {
                    // Init&deploy infrastructre
                    sh '''
                        terraform init -input=false
                        terraform apply -auto-approve
                    '''
                }
            }
        }

        stage('Extract Terraform Outputs') {
            steps {
                dir("./task_2/${TF_DIR}") {
                    script {
                        // Get outputs in JSON format
                        def tf_output = sh(script: 'terraform output -json', returnStdout: true).trim()
                        def parsed = readJSON text: tf_output

                        // Extract values
                        def web_ips = parsed.web_server_ips.value
                        def db_endpoint = parsed.db_endpoint.value

                        // Print for visibility
                        echo "Web IPs: ${web_ips}"
                        echo "DB Endpoint: ${db_endpoint}"
                    }
                }
            }
        }
    }

    post {
        failure {
            dir("./task_2/${TF_DIR}") {
                echo "Pipeline failed. Terraform detroy"
                sh '''
                        terraform destroy -auto-approve
                    '''
                }
        }
    }
}


